backend:
  name: "github"
  repo: "PauseAI/pauseai-website"
  branch: "main"
  open_authoring: true
  base_url: "https://pauseai-cms-proxy.netlify.app"
  squash_merges: true
publish_mode: "editorial_workflow"
media_folder: "/static"
editor:
  preview: false
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/posts"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "slug"
        label: "Slug"
        widget: "string"
        required: false
      - name: "description"
        label: "Description"
        widget: "string"
        required: false
      - name: "image"
        label: "Image"
        widget: "image"
        required: false
      - name: "author"
        label: "Author"
        widget: "string"
        required: false
      - name: "date"
        label: "Date"
        widget: "datetime"
        required: false
      - name: "body"
        widget: "markdown"
