backend:
  name: "github"
  repo: "PauseAI/pauseai-website"
  branch: "main"
  open_authoring: true
  base_url: "https://pauseai-cms-proxy.netlify.app"
  squash_merges: true
publish_mode: "editorial_workflow"
media_folder: "/static"
editor:
  preview: false
collections:
  - name: "posts"
    label: "Posts"
    label_singular: "Post"
    folder: "src/posts"
    create: true
    slug: "{{fields.slug}}"
    fields:
      - name: "title"
        label: "Title"
        widget: "string"
      - name: "slug"
        label: "Slug"
        widget: "string"
        required: false
      - name: "description"
        label: "Description"
        widget: "string"
        required: false
      - name: "image"
        label: "Image"
        widget: "image"
        required: false
      - name: "author"
        label: "Author"
        widget: "string"
        required: false
      - name: "date"
        label: "Date"
        widget: "datetime"
        required: false
      - name: "body"
        widget: "markdown"
  - label: "Communities"
    description: "Shown on pauseai.info/communities"
    name: "communities"
    files:
      - label: "PauseAI communities"
        name: "pauseai"
        file: "src/routes/communities/pauseai-communities.json"
        fields:
          - label: Communities
            name: communities
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Latitude, name: lat, widget: number }
              - { label: Longitutde, name: lon, widget: number }
              - {
                  label: Link,
                  name: link,
                  widget: string,
                  hint: "**Available placeholders:** $$DISCORD_GLOBAL$$, $$DISCORD_US$$, $$DISCORD_GERMANY$$, $$DISCORD_FRANCE$$, $$WHATSAPP_ITALY$$",
                }
      - label: "Adjacent communities"
        name: "adjacent"
        file: "src/routes/communities/adjacent-communities.json"
        fields:
          - label: Communities
            name: communities
            widget: list
            fields:
              - { label: Name, name: name, widget: string }
              - { label: Latitude, name: lat, widget: number }
              - { label: Longitutde, name: lon, widget: number }
              - { label: Link, name: link, widget: string }
